// Mocks generated by Mockito 5.0.15 from annotations
// in eshop_flutter/test/screens/order_detail_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:eshop_flutter/core/models/order_model.dart' as _i2;
import 'package:eshop_flutter/core/services/order_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeOrder_0 extends _i1.Fake implements _i2.Order {}

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i3.OrderService {
  MockOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.OrderList>> getOrders() =>
      (super.noSuchMethod(Invocation.method(#getOrders, []),
              returnValue: Future<List<_i2.OrderList>>.value(<_i2.OrderList>[]))
          as _i4.Future<List<_i2.OrderList>>);
  @override
  _i4.Future<_i2.Order> getDetailOrder(String? orderId) =>
      (super.noSuchMethod(Invocation.method(#getDetailOrder, [orderId]),
              returnValue: Future<_i2.Order>.value(_FakeOrder_0()))
          as _i4.Future<_i2.Order>);
  @override
  _i4.Future<_i2.Order> finishOrder(String? orderId) =>
      (super.noSuchMethod(Invocation.method(#finishOrder, [orderId]),
              returnValue: Future<_i2.Order>.value(_FakeOrder_0()))
          as _i4.Future<_i2.Order>);
  @override
  String toString() => super.toString();
}
