// Mocks generated by Mockito 5.0.11 from annotations
// in moviedb/test/screens/movie_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:eshop_flutter/core/models/async_state.dart' as _i2;
import 'package:eshop_flutter/core/models/shoe.dart' as _i3;
import 'package:eshop_flutter/product_detail/view_model/size_state_view_model.dart'
as _i4;

import 'package:eshop_flutter/product_detail/view_model/product_detail_view_model.dart'
as _i6;
import 'package:eshop_flutter/product_detail/view_model/color_state_view_model.dart'
as _i8;
import 'package:eshop_flutter/product_detail/view_model/color_available_view_model.dart'
as _i9;
import 'package:state_notifier/state_notifier.dart' as _i5;
import 'package:eshop_flutter/core/services/shoe_service.dart' as _i7;

class _FakeAsyncState<T> extends _i1.Fake implements _i2.AsyncState<T> {}
class _FakeShoeDetail extends _i1.Fake implements _i3.ShoeDetail {}


class MockShoeService extends _i1.Mock implements _i7.ShoeService {
  MockShoeService() {
    _i1.throwOnMissingStub(this);
  }
  @override
  _i6.Future<_i3.ShoeDetail> getShoeDetail(String? shoeId) =>
      (super.noSuchMethod(Invocation.method(#getShoeDetail, [shoeId]),
          returnValue: Future<_i3.ShoeDetail>.value(_FakeShoeDetail()))
      as _i6.Future<_i3.ShoeDetail>);
}

class MockSizeViewModel extends _i1.Mock
    implements _i4.SizeViewModel {
  MockSizeMovieViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i5.ErrorListener? _onError) =>
      super.noSuchMethod(Invocation.setter(#onError, _onError),
          returnValueForMissingStub: null);
  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
      as bool);
  @override
  _i6.Stream<int> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
          returnValue: Stream<int>.empty())
      as _i6.Stream<int>);
  @override
  int get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: (int)));
  @override
  set state(int? value) =>
      super.noSuchMethod(Invocation.setter(#state, value),
          returnValueForMissingStub: null);
  @override
  int get debugState =>
      (super.noSuchMethod(Invocation.getter(#debugState),
          returnValue: (int)));
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
      as bool);
  @override
  void loadData() => super.noSuchMethod(Invocation.method(#loadData, []),
      returnValueForMissingStub: null);
  @override
  _i5.RemoveListener addListener(
      _i5.Listener<int>? listener,
      {bool? fireImmediately = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addListener, [listener], {#fireImmediately: fireImmediately}),
          returnValue: () {}) as _i5.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}

class MockProductDetailViewModel extends _i1.Mock
    implements _i6.ProductDetailViewModel {
  MockProductDetailViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i5.ErrorListener? _onError) =>
      super.noSuchMethod(Invocation.setter(#onError, _onError),
          returnValueForMissingStub: null);
  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
      as bool);
  @override
  _i6.Stream<_i2.AsyncState<_i3.ShoeDetail>> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
          returnValue: Stream<_i2.AsyncState<_i3.ShoeDetail>>.empty())
      as _i6.Stream<_i2.AsyncState<_i3.ShoeDetail>>);
  @override
  _i2.AsyncState<_i3.ShoeDetail> get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeAsyncState<_i3.ShoeDetail>())
      as _i2.AsyncState<_i3.ShoeDetail>);
  @override
  set state(_i2.AsyncState<_i3.ShoeDetail>? value) =>
      super.noSuchMethod(Invocation.setter(#state, value),
          returnValueForMissingStub: null);
  @override
  _i2.AsyncState<_i3.ShoeDetail> get debugState =>
      (super.noSuchMethod(Invocation.getter(#debugState),
          returnValue: _FakeAsyncState<_i3.ShoeDetail>())
      as _i2.AsyncState<_i3.ShoeDetail>);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
      as bool);
  // @override
  // void loadData('keyword') => super.noSuchMethod(Invocation.method(#loadData, ['keyword']),
  //     returnValueForMissingStub: null);
  @override
  _i5.RemoveListener addListener(
      _i5.Listener<_i2.AsyncState<_i3.ShoeDetail>>? listener,
      {bool? fireImmediately = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addListener, [listener], {#fireImmediately: fireImmediately}),
          returnValue: () {}) as _i5.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}

class MockColorViewModel extends _i1.Mock
    implements _i8.ColorViewModel {
  MockColorViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i5.ErrorListener? _onError) =>
      super.noSuchMethod(Invocation.setter(#onError, _onError),
          returnValueForMissingStub: null);
  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
      as bool);
  @override
  _i6.Stream<int> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
          returnValue: Stream<int>.empty())
      as _i6.Stream<int>);
  @override
  int get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: (int)));
  @override
  set state(int? value) =>
      super.noSuchMethod(Invocation.setter(#state, value),
          returnValueForMissingStub: null);
  @override
  int get debugState =>
      (super.noSuchMethod(Invocation.getter(#debugState),
          returnValue: (int)));
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
      as bool);
  @override
  void loadData() => super.noSuchMethod(Invocation.method(#loadData, []),
      returnValueForMissingStub: null);
  @override
  _i5.RemoveListener addListener(
      _i5.Listener<int>? listener,
      {bool? fireImmediately = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addListener, [listener], {#fireImmediately: fireImmediately}),
          returnValue: () {}) as _i5.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}

class MockColorAvailableViewModel extends _i1.Mock
    implements _i9.ColorAvailableViewModel {
  MockColorAvailableViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i5.ErrorListener? _onError) =>
      super.noSuchMethod(Invocation.setter(#onError, _onError),
          returnValueForMissingStub: null);
  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
      as bool);
  @override
  _i6.Stream<_i2.AsyncState<List<int>>> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
          returnValue: Stream<_i2.AsyncState<List<int>>>.empty())
      as _i6.Stream<_i2.AsyncState<List<int>>>);
  @override
  _i2.AsyncState<List<int>> get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeAsyncState<List<int>>())
      as _i2.AsyncState<List<int>>);
  @override
  set state(_i2.AsyncState<List<int>>? value) =>
      super.noSuchMethod(Invocation.setter(#state, value),
          returnValueForMissingStub: null);
  @override
  _i2.AsyncState<List<int>> get debugState =>
      (super.noSuchMethod(Invocation.getter(#debugState),
          returnValue: _FakeAsyncState<List<int>>())
      as _i2.AsyncState<List<int>>);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
      as bool);
  @override
  void loadData() => super.noSuchMethod(Invocation.method(#loadData, []),
      returnValueForMissingStub: null);
  @override
  _i5.RemoveListener addListener(
      _i5.Listener<_i2.AsyncState<List<int>>>? listener,
      {bool? fireImmediately = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addListener, [listener], {#fireImmediately: fireImmediately}),
          returnValue: () {}) as _i5.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}