// Mocks generated by Mockito 5.0.15 from annotations
// in eshop_flutter/test/screens/profile_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:eshop_flutter/core/models/profile_model.dart' as _i2;
import 'package:eshop_flutter/core/services/profile_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeProfileModel_0 extends _i1.Fake implements _i2.ProfileModel {}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i3.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProfileModel> getProfile() => (super.noSuchMethod(
          Invocation.method(#getProfile, []),
          returnValue: Future<_i2.ProfileModel>.value(_FakeProfileModel_0()))
      as _i4.Future<_i2.ProfileModel>);
  @override
  _i4.Future<_i2.ProfileModel> logOut() => (super.noSuchMethod(
          Invocation.method(#logOut, []),
          returnValue: Future<_i2.ProfileModel>.value(_FakeProfileModel_0()))
      as _i4.Future<_i2.ProfileModel>);
  @override
  String toString() => super.toString();
}
